# Nombre de la librería
NAME = libft.a

# Compilador y flags
CC = gcc
CFLAGS = -Wall -Wextra -Werror

# # List of source files for the functions
# FUNCTIONS = ft_atoi.c \
#            ft_bzero.c \
#            ft_calloc.c \
#            ft_isalnum.c \
#            ft_isalpha.c \
#            ft_isascii.c \
#            ft_isdigit.c \
#            ft_isprint.c \
#            ft_itoa.c \
#            ft_memchr.c \
#            ft_memcmp.c \
#            ft_memcpy.c \
#            ft_memmove.c \
#            ft_memset.c \
#            ft_putchar_fd.c \
#            ft_putendl_fd.c \
#            ft_putnbr_fd.c \
#            ft_putstr_fd.c \
#            ft_split.c \
#            ft_strchr.c \
#            ft_strdup.c \
#            ft_striteri.c \
#            ft_strjoin.c \
#            ft_strlcat.c \
#            ft_strlcpy.c \
#            ft_strlen.c \
#            ft_strmapi.c \
#            ft_strncmp.c \
#            ft_strnstr.c \
#            ft_strrchr.c \
#            ft_strtrim.c \
#            ft_substr.c \
#            ft_tolower.c \
#            ft_toupper.c

# Archivos fuente y sus correspondientes archivos objeto
SRCS = $(wildcard *.c)
OBJS = $(SRCS:.c=.o)

# Archivo de cabecera
HEADER = libft.h

# Regla principal (crear la librería)
all: $(NAME)

# Crear la librería estática
$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

# Regla para compilar los archivos objeto
%.o: %.c $(HEADER)
	$(CC) $(CFLAGS) -c $< -o $@

# Limpiar archivos objeto
clean:
	rm -f $(OBJS)

# Limpiar todo (archivos objeto y librería)
fclean: clean
	rm -f $(NAME)

# Reconstruir todo desde cero
re: fclean all

# Evita que Make interprete estos nombres como archivos o directorios
.PHONY: all clean fclean re
